import { Accordion, AccordionItem, AccordionHeader } from 'reactstrap';

const Covenants = () => {
    return (
        <div className="main" style={{ width: "100%" }}>
        <h1 style={{paddingLeft: "15px"}}>Covenants and Bylaws</h1>
            <div>
            <Accordion className="covenants" toggle={function noRefCheck() { }}>
            <AccordionItem>
                <AccordionHeader targetId="1">
                Article I - Definitions
                </AccordionHeader>
                <AccordionItem accordionId="1">
                    <p><strong>Section 1. </strong>'Association' shall mean and refer to the Park Ridge Community Association.</p>
                    <p><strong>Section 2. </strong>'Bylaws' shall mean the Bylaws initially adopted by Park Ridge Community Association, Inc., and all amendments and additions thereto.</p>
                    <p><strong>Section 3. </strong>'Committee' shall mean the Architectural Control Committee, composed of three members appointed by the Developer and who shall be subject to removal by the Developer at any time with or without cause. Any vacancies from time to time shall be filled by appointment of the Developer.</p>
                    <p><strong>Section 4. </strong>'Common Area' shall mean all real property owned by the Association for the common use and enjoyment of the Owners.</p>
                    <p><strong>Section 5. </strong>'Developer' shall mean and refer to Park Ridge Developers, LLC its successors and assigns.</p>
                    <p><strong>Section 6. </strong>'Dwelling Unit' shall mean and refer to the structure used as a residential living unit located upon a Lot, including the garage and any appurtenances.</p>
                    <p><strong>Section 7. </strong>'Lot' shall mean either any of said Lots as platted or any tract or tracts of land as conveyed originally or by subsequent Owners, which may consist of one or more Lots or parts of one or more Lots as platted upon which a residence may be erected in accordance with the restrictions hereinabove set out or such further restrictions as may be imposed by any applicable zoning ordinance, PROVIDED, HOWEVER, no tract of land consisting of part of any one Lot or parts of more than one Lot shall be considered a 'LOT' unless said tract of land has a frontage of 50 feet in width at the established building line as shown on this plat.</p>
                    <p><strong>Section 8. </strong>'Park Ridge' shall mean and refer to the name by which the real estate, which is the subject of this Declaration or any subsequent declaration of any additional section of Park Ridge, shall be known.</p>
                    <p><strong>Section 9. </strong>'Owner' shall mean and refer to the record Owner, whether one or more persons or entities, of a fee simple title to any Lot which is a part of the Properties, including contract sellers, but excluding those having such interest merely as security for the performance of an obligation.</p>
                    <p><strong>Section 10. </strong>'Properties' shall mean and refer to that certain real property herinbefore described, and such additions thereto as may hereafter be brought within the jurisdiction of the Association by the Developer as additional sections of Park Ridge.</p>
                    <p><strong>Section 11. </strong>'Restrictions' shall mean and refer to the Dedication, Protective Restrictions, Covenants, Limitations, Easements, and Approvals appended to as part of the Dedication and Plat of Park Ridge, Section II.</p>
                    <p><strong>Section 12. </strong>'Subdivision' shall mean Park Ridge, Section II, a subdivision in Wayne Township, Kosciusko County, Indiana.</p>
                </AccordionItem>
            </AccordionItem>
            <AccordionItem>
                <AccordionHeader targetId="2">
                Article II - Property Rights
                </AccordionHeader>
                <AccordionItem accordionId="2">
                    <p><strong>Section 1. Owners' Easements of Enjoyment </strong>Every Owner shall have a right and easement of enjoyment in and to the Common Area which shall be appurtenant to and shall pass with the title to every Lot, subject to the following provisions:
                        <ol type="a">
                            <li>the right of the Association to charge reasonable admission and other fees for the use of any recreational facility situated upon the Common Area;</li>
                            <li>the right of the Association to suspend the voting rights and right to the use of the recreational facilities by an Owner for any period during which any assessments against his Lot remains unpaid; and for a period not to exceed 30 days for any infraction of its published rules and regulations after hearing by the Board of Directors of the Association;</li>
                            <li>easements reserved herin for any public agency or authority and any utility for the installation and maintenance of surface drainage facilities and underground utilities serving or benefiting any of the properties.</li>
                            <li>the right of the Association to dedicate or transfer all or any part of the Common Area to any public agency, authority, or utility for such purposes and subject to such conditions as may be agreed to by the members. No such dedication or transfer shall be effective unless an instrument signed by two-thirds (2/3) of each class of members agreeing to such dedication or transfer has been recorded.</li>
                            <li>any Common Areas located between a Lot line and the waters edge of a lake or pond, as shown on the Plat, any ingress and egress to such Common Areas shall be restricted solely to the Lot Owner, the Association, or any public or quasi-public agencies. All such Commons Areas located between a Lot line and the waters edge of a lake or pond shall be for the sole use, enjoyment and benefit of the respective Lot Owner to the exclusion of all other Lot Owners.</li>
                        </ol>
                    </p>
                    <p><strong>Section 2. Delegation of Use </strong>Any Owner may delegate, in accordance with the Bylaws, his right of enjoyment to the Common Area and facilities to the members of his family, his tenants, or contract purchasers who reside on the property.</p>    
                </AccordionItem>
            </AccordionItem>
            <AccordionItem>
                <AccordionHeader targetId="3">
                Article III - Association Membership and Voting Rights
                </AccordionHeader>
                <AccordionItem accordionId="3">
                    <p><strong>Section 1. </strong>Every Owner of a Lot shall be a member of the Association. Membership shall be appurtenant to and may not be separated from Ownership of any Lot which is subject to assessment.</p>
                    <p><strong>Section 2. </strong>The Association shall have two classes of voting memberships:
                        <ul>
                            <li><strong>Class A. </strong>Class A members shall be all Owners of Lots in Park Ridge other than Developer and such members shall be entitled to one vote for each Lot owned. When more than one person holds an interest in any Lot, all such persons shall be members. The vote for such Lot shall be exercised as they among themselves determine, but in no event shall more than one vote be cast with respect to any one Lot.</li>
                                    <li><strong>Class B. </strong>Class B member(s) shall be the Developer, and such member(s) shall be entitled to five (5) votes for each Lot owned. The Class B membership shall cease and be converted to Class A membership on the happening of either of the following events, whichever occurs earlier:
                                        <ol type="a">
                                            <li>when title to all Lots in all sections of Park Ridge have been conveyed, or on December 31, 2015.</li>
                                        </ol>
                            </li>
                        </ul>
                    </p>
                </AccordionItem>
            </AccordionItem>
            <AccordionItem>
                <AccordionHeader targetId="4">
                Article IV - Covenant for Maintenance Assessments
                </AccordionHeader>
                <AccordionItem accordionId="4">
                    <p><strong>Section 1. Creation of the Lien and Personal Obligation of Assessments </strong>Each Owner of any Lot, excepting the Developer, by acceptance of a deed therefore, whether or not it shall be so expressed in such deed, is deemed to covenant and agree to pay to the Association: (1) annual assessments or charges, (2) special assessments for capital improvements; and (3) lot maintenance assessments or charges; such assessments to be established and collected as hereinafter provided. Assessments or any installments thereof which are not paid when due shall bear interest at a fluctuating rate equal to the maximum rate of interest which may be charged under the laws of the State of Indiana for consumer loans, adjusted on the first day of each calendar year. If any Owner shall fail, refuse, or neglect to make any payment of any Assessment when due, the Board of Directors of the Association may in its discretion declare the entire balance of unpaid Assessments to be due and payable, with interest as aforesaid, and file a written Notice of Lien against said Owner's Lot in the office of the Recorder of Kosciusko County, Indiana, which Notice of Lien shall perfect the lien of the Association and have the same force and effect as, and be enforced in the same manner as, a mortgage lien under Indiana law, and shall include attorney's fees, title expenses, interest, and any costs of collection.</p>
                    <p><strong>Section 2. Purpose of Assessments </strong>The assessments levied by the Association shall be used exclusively for the purpose of promoting the recreation, health, safety, and welfare of residents of Park Ridge, and in particular for the maintenance of any Lot prior to the commencement of construction of a Dwelling Unit thereon, and for the improvement, operation and maintenance of any storm water detention basin along with any water level control structurs and all other Common Areas, including but not limited to, repair, maintenance, lighting, street signs, lawn care, snow removal, insurance, taxes, and all other things necessary or desirable in the opinion of the Board of Directors of the Association in connection therewith.</p>
                    <p><strong>Section 3. Maximum Annual Assessments </strong>Until January 1 of the year immediately following the conveyance by the Developer of the first Lot to an Owner, the maximum annual assessment shall be Two Hundred Dollars ($200.00) per Lot.
                        <ol type="a">
                            <li>From and after January 1 of the year immediately following the conveyance of the first Lot to an Owner, the maximum annual assessment may be increased each year not more than 15% above the maximum assessment for the previous year without a vote of the membership.</li>
                            <li>From and after January 1 of the year immediately following the conveyance of the first Lot to an Owner, the maximum annual assessment may be increased above 15% by the affirmative vote or written assent of 51% of each class of members.</li>
                            <li>The Board of Directors may fix the annual assessment at an amount not in excess of the maximum.</li>
                        </ol>
                    </p>
                    <p><strong>Section 4. Special Assessments for Capital Improvements </strong>In addition to the annual assessments authorized above, the Association may levy, in any assessment year, a special assessment applicable to that year only for the purpose of defraying, in whole or in part, the cost of construction, repair, or replacement of a capital improvement upon the Common Area, including fixtures and personal property related thereto, provided that any such assessment shall have the affirmative vote or written assent of 51% of each class of members.</p>
                    <p><strong>Section 5. Notice and Quorum For Any Action Authorized Under Section 3 and 4 </strong>Any action authorized under Sections 3 or 4 and requiring an affirmative vote or written assent of a certain percentage of the Association membership shall be taken at a meeting called for that purpose, written notice of which shall be sent to all members not less than 30 days nor more than 60 days in advance of the meeting. If the proposed action is favored by a majority of the votes cast at such meeting, but such vote is less than the requisite 51% of each class of members, members who were not present in person or by proxy may give their assent in writing, provided the same is obtained by the appropriate officers of the Association not later than 30 days from the date of such meeting.</p>
                    <p><strong>Section 6. Uniform Rate of Assessment </strong>Both annual and special assessments must be fixed at a uniform rate for all Lots and may be collected on a monthly, quarterly, or yearly basis.</p>
                    <p><strong>Section 7. Date of Commencement of Annual Assessments: Due Dates </strong>The annual assessments provided for herin shall commence as to all Lots on the first day of the month following the first conveyance of Common Area by the Developer to the Association. The first annual assessment shall be adjusted according to the number of months remaining in the calendar year. The Board of Directors shall fix the amount of the annual assessment against each Lot at least thirty (30) days in advance of each annual assessment period. Written notice of the annual assessment shall be sent to every Owner subject thereto. The Association shall, upon demand and for a reasonable chrage, furnish a certificate signed by an office of the Association setting forth whether the assessments on a specified Lot have been paid.</p>
                    <p><strong>Section 8. Lot Maintenance Assessment </strong>From and after the date construction of a single-family residence commences upon a Lot, it shall be the duty of the Lot Owner to perform all maintenance on the Lot, including but not limited to, cutting the grass, keeping the Lot free from weeds, and the removal of all trash and debris.</p>
                    <p><strong>Section 9. Effect of Nonpayment of Assessments: Remedies of the Association </strong>Any assessment or other charge not paid within thirty (30) days after the due date shall bear interest from the due date as provided in Section 1 of this Article IV. The Association may brng an action at law against the Owner personally obligated to pay the same; may foreclose the lien against the owner's lot in accordance with the provisions of Section 1 of this Article IV; or may do both. No Owner may waive or otherwise escape personal liability for the assessments provided for herein by nonuse of the Common Area or abandonment of his Lot.</p>
                    <p><strong>Section 10. Subordination of the Lien to Mortgages </strong>The lien of the assessments provided for herin shall be subordinate to the lien of any first mortgage. Sale or transfer of any Lot shall not affect the assessment lien. However, the sale or transfer of any Lot pursuant to a judgment and court order on a foreclosure of any first mortgage shall extinguish the lien of such assessments as to payments which became due prior to such sale or transfer. No such sale or transfer shall relieve such Lot from liability for any assessments thereafter becoming due or from the lien thereof.</p>        
                </AccordionItem>
            </AccordionItem>
            <AccordionItem>
                <AccordionHeader targetId="5">
                Article V - Architectural Control
                </AccordionHeader>
                <AccordionItem accordionId="5">
                <p>No building, fence, wall, deck, swimming pool or spa, or other structure shall be commenced, erected, or maintained upon any Lot, nor shall any exterior addition to or change or alteration therein be made until two sets of plans and specifications showing: (1) the location of improvements of the lot (site plan); (2) the location of the driveway on the site plan; (3) front, rear, and side elevations shall have been submitted to and approved in writing as to harmony of external design and location in relation to surrounding structures and topography by the Architectural Control Committee. The Committee's approval or disapproval, as required in these covenants, shall be in writing. In the even the Committee fails to approve or disapprove such plans within 60 days after receipt, such plans shall be deemed approved. No structure of any kind which does not comply fully with such approved plans shall be errected, constructed, placed or maintained upon any Lot, and no changes or deviations in or from such plans as approved shall be made without the Committee's prior written consent. Neither the Developer, the Architectural Control Committee, nor any member thereof, nor any of their respective heirs, personal representatives, successors, or assigns shall be liable to anyone by reason of any mistake in judgment, negligence, or nonfeasance arising out of or relating to the approval or disapproval or failure to approve any plans so submitted, nor shall they, or any of them, be responsible or liable for any structural defects in such plans or in any building or structure erected according to such plans or any drainage problems resulting there from. Every person and entity who submits plans to the Architectural Control Committee agrees, by submission of such plans, that he or it will not bring any action or suit against the Committee or the Developer to recover any damages or to require the Committee or the Developer to take, or refrain from taking, any action whatever in regard to such plans or in regard to any building or structure erected in accordance therewith. Neither the submission of any complete set(s) of plans to the Developer's office for review by the Architectural Control Committee, nor the approval thereof by that Committee, shall be deemed to guarantee or require the actual construction of the building of structure therin described, and no adjacent Lot Owner may claim any reliance upon the submission and/or approval of any such plans or the buildings or structures described therin. In the event the Committee or the Association shall prevail in any litigation brought for the purpose of enforcing compliance with the provisions of this Article V, it shall be entitled to recover from the defendants reasonable attorney fees and costs incurred in such enforcement.</p>
                </AccordionItem>
            </AccordionItem>
                <AccordionItem>
                <AccordionHeader targetId="6">
                Article VI - General Provisions
                </AccordionHeader>
                <AccordionItem accordionId="6">
                <p><strong>Section 1. Residential Purposes. </strong>
                No Lot shall be used except for residential purposes. No building shall be erected, altered, placed, or permitted to remain on any Lot other than one detached single-family dwelling not to exceed two and one-half stories in height. Each Dwelling Unit shall include not less than a two car garage, which shall be built as part of said structure and attached thereto.</p>
                <p><strong>Section 2. Home Occupations </strong>No Lot shall be used for any purpose other than as a signle-family residence, except by approval of the Developer a builder may use his/her home as a model and/or sales center for other homes he/she is building in Park Ridge, and except that a home occupation, defined as follows may be permitted: any use conducted entirely within the Dwelling Unit and participated in solely by a member of the immediate family residing in said Dwelling Unit, which use is clearly incidental and secondary to the use of the Dwelling Unit for dwelling purposes and does not change the character thereof and in connection with which there is: (a) no sign or display that indicates from the exterior that the Dwelling Unit is being utilized in whole or in part for any purpose other than that of a Dwelling Unit; (b) no commodity is sold upon the Lot; (c) no person is employed in such home occupation other than a member of the immediate family residing in the Dwelling Unit; and (d) no mechanical or electrical equipment is used; provided that, in no event shall a barber shop, styling salon, beauty parlor, tea room, fortune-telling parlor, licensed child care center or other licensed or regulated baby-sitting service, any type of auto repair services, animal hospital, or any form of animal care or treatment such as dog trimming, breeding or kennel be construed as a home occupation.</p>
                <p><strong>Section 3. Single Owner Contiguous Lots </strong>Whenever two (2) or more contiguous Lots in the Subdivision shall be owned by the same person, and such Owner shall desire to use two or more of said Lots as a site for a single Dwelling Unit, he shall apply in writing to the Architectural Control Committee or Board of Directors of the Association for permission to so use said Lots. If permission for such a use shall be granted, the Lots constituting the site for each single Dwelling Unit shall be treated as a single Lot for the purpose of applying these Restrictions to said Lots, so long as the Lots remain improved with one single Dwelling Unit.</p>
                <p><strong>Section 4. Subdivision of Lots </strong>No lot or combination of Lots may be further subdivided unless 75% of the Lot Owners have approved by signing an instrument of approval and until said approval has been obtained from the City of Warsaw Plan Commission, or its successors.</p>
                <p><strong>Section 5. Improvements </strong>Before any Dwelling Unit on any Lot in this Subdivision shall be used and occupied as a dwelling or otherwise, the Developer or any subsequent Owner of such Lot shall install improvements serving such Lot as provided in the plans and specifications for such improvements filed with the appropriate governmental authorities may authorize or require. This covenant shall run with the land and be enforceable by any governmental authority having jurisdiction over the Subdivision, by the Association, or by any aggrieved Lot Owner in this Subdivision.</p>
                <p><strong>Section 6. Permits and Certificates </strong>Before any Dwelling Unit located on any Lot may be used or occupied, such user or occupier shall first obtain from the City of Warsaw Zoning Administrator an Improvement Location Permit and a Certificate of Occupancy as required by the City of Warsaw Zoning Ordinance.</p>
                <p><strong>Section 7. Time for Building Completion </strong>Every Dwelling Unit on any Lot in the Subdivision shall be completed within twelve (12) months after the beginning of such construction.</p>
                <p><strong>Section 8. Building Sizes </strong>No Dwelling Unit shall be built on any Lot having a living area of the main structure, exclusive of one-story open porches, breezeways, or garages of less than 1,200 square feet for a one-story Dwelling Unit, nor less than 1,500 square feet for a two story dwelling unit.</p>
                <p><strong>Section 9. Garages </strong>All Dwelling Units must have at least a full-size, attached, two-car garage.</p>
                <p><strong>Section 10. Building Setback </strong>No Dwelling Unit or any improvements or structures shall be located on any Lot nearer to the front Lot line or nearer to the side street line or the rear lot line than the minimum building setback lines shown on the recorded plat. In any event, no Dwelling Unit shall be located no nearer than a distance of seven (7) feet to a side Lot line, and no nearer than a distance of twenty-five (25) feet to a rear lot line if there ise no rear setback line shown on the recorded plat.</p>
                <p><strong>Section 11. Minimum Lot Size </strong>The minimum Lot size for the placement of a dwelling unit is 8,750 square feet. The minimum width at the building setback line of a Lot is 50 feet.</p>
                <p><strong>Section 12. Building Materials </strong>All Dwelling Units and other permitted structures shall be constructed in a substantial and good workmanlike manner and of new materials. No roll siding, asbestos siding, or siding containing asphalt or tar as one of its principal ingredients shall be used in the exterior construction any Dwelling Unit or other permitted structure on any Lot, and no roll roofing of any description or character shall be used on the roof of any Dwelling Unit or other permitted structure on any of said Lots.</p>
                <p><strong>Section 13. Yard Light </strong>An automatic dusk-to-dawn light of a type and at a location approved by the Architectural Control Committee shall be isntalled by the builder or Lot Owner on each Lot in front of the front building line.</p>
                <p><strong>Section 14. Driveways </strong>All driveways from the street to the garage shall be poured concrete and not less than sixteen (16) feet in width.</p>
                <p><strong>Section 15. Sidewalks </strong>Plans and specifications for this Subdivision on file with the City of Warsaw Plan Commission require the installation of concrete sidewalks within the street rights-of-way in front of all Lots.<br />
                Installation of said sidewalks shall be the obligation of the Owner of any such Lot, exclusive of the Developer and shall be completed in accordance with said plans and specifications and prior to the issuance of a Certificate of Occupancy for any such Lot. The cost of installation shall be a lien against such Lot enforceable by the City of Warsaw Plan Commission or its successor agency. Should such Certificates of Occupancy be issued to the Developer, said Developer shall be considered an Owner for the purposes of the enforcement of this covenant.</p>
                <p><strong>Section 16. Fencing </strong>Except as provided in the following sentence, the only fencing permitted shall be a split rail (two rails high) or a picket fence, either no to exceed four feet high or a privacy fence around an immediate patio of not more than six feet all of which must be approved by the Architectural Control Committee in writing, unless a variance from this fence requirement shall have been approved in writing by the Architectural Control Committee. In the event a pool or hot tub is installed on any Lot, a five-foot safety fence, if required by law, may be installed with the approval of the Architectural Control Committee.</p>
                <p><strong>Section 17. Pools and Hot Tubs </strong>No above ground pool which requries a filtration system or other above ground pool which is more than six (6) feet in diameter and 18 inches deep shall be placed or maintained on any Lot without the prior written approval of the Architectural Control Committee in accordance with Article V. At the time of installation of any type of pool or hot tub safety fencing must also be installed in accordance to Article VI, Section 16.</p>
                <p><strong>Section 18. Mailboxes </strong>The location on a mailbox station is provided for each lot. The purchase and installation of the mailbox is the responsibility of the homeowner. A standard, black, type T1, loaf shape mailbox is required.</p>
                <p><strong>Section 19. Radio and Television Antennas </strong>No radio or television antenna with more than thirty (30) square feet of grid area or which attains a height of six (6) feet above the highest point of the roof shall be attached to any Dwelling Unit. No radio, television antenna or receiving dish shall be permitted on any Lot or any Dwelling Unit without the approval of the Architectural Control Committee.</p>
                <p><strong>Section 20. Duty to Repair and Rebuild </strong>
                    <ol type="a">
                                    <li>Each Lot Owner shall, at his sole cost and expense, repair his Dwelling Unit, keeping the same in a condition comparable to the condition of such Dwelling Unit at the time its initial construction was completed, excepting only usual wear and tear.</li>
                                    <li>If all or any portion of a Dwelling Unit is destroyed by fire or other casualty then the Owner shall, with all due diligence, promptly rebuild, repair, or reconstruct such Dwelling Unit in a manner which will substantially retore it to its condition as existed immediately prior to the casualty. No impovement upon a Lot, which has been partially or totally destroyed by fire or other casualty, shall remain in such condition for more than three (3) months from the time such destruction or damage occurred.</li>
                    </ol>
                </p>
                <p><strong>Section 21. Utility and Underground Drainage Easements </strong>Easements for the installation and maintenance of utilities and underground drainage facilities are reserved as shown on the recorded plat. No Owner of any Lot shall erect or grant to any person, firm, or corporation, the right, license, or privilege to erect or use or permit the use of overhead wires, poles, or television service (except such poles and overhead facilities that may ber required at those places where distribution facilities enter and leave the subdivision). Nothing herein shall be construed to prohibit street lighting or ornamental yard lighting serviced by underground wires or cables. The Owners of all Lots shall provide electrical service entrance facilities installed for any Dwelling Unit or other structure connecting the same to the electrical distribution system of any electric public utility. Any electric public utility charged with the maintenance of any underground installation shall have access to all easements in which said underground installations are located for operation, maintenance, and replacement of service connections. Any such electric public utility shall not be liable for damage to walks, driveways, lawn, or landscaping which may result from installation, repair, or maintenance of such service.</p>
                <p><strong>Section 22. Surface Drainage </strong>Surface Drainage Easements, Storm water Detention Basins and Common Areas used for drainage purposes, as shown on the plat, are intended for either periodic or occassional use as conductors for the flow of suface water runoff to a suitable outlet and the land surfact shall be ocnstructed and maintained so as to achieve this intention. Such easements ahll be maintained in an unobstructed and proper working condition during and after construction and the County Surveyor or a proper public authority having jurisdiction over storm drainage shall have the right to determine if any obstruction exists and to repair and maintain or to require such repair and maintenance as shall be reasonably necessary to keep the conductors unobstructed and operable. It shall be the responsibility of the builder and/or the home buyers to inspect rear and side swales for positive drainage coniditions prior to closing on the lot. The developer shall be relieved of any responsibility for repair of the swales on the lot following the closing of the lot to either the builder or the home buyer.</p>
                <p><strong>Section 23. Use of Public Easements </strong>In addition to the utility easements herein designated, easements in the streets shown on this plat are hereby reserved and granted to the Developer, the Association, and public or quasi-public utility company engaged in supplying one or more of the utility services contemplatedin Sections 21 and 22 or this Section 23 of Article VI, and their respective successors and assigns, to install, lay, erect, construct, renew, operate, repair, replace, maintain, and remove all and every type of gas main, water main, and sewer main (sanitary and/or storm) with all necessary appliances, subject, nevertheless, to all reasonable requirements of any governmental body having jurisdiction thereof as to maintenance and repair of said streets.</p>
                <p><strong>Section 24. Individual Water and Sewage Systems </strong>No individual water supply system or individual sewage disposal system shall be installed, maintained, or used on any Lots.</p>
                <p><strong>Section 25. Sanitary Sewer Restrictions </strong>No rain or storm water runoff or such things as sump pump water discharge, roof water, street pavement, and surfact water, caused by natural precipitation, shall at any time be discharged into or permitted to flow into the Sanitary Sewage System, which shall be a separate sewer system from the Storm Water and Surfact Water Runoff Sewer System. No sanitary sewage shall at any time be discharged or permitted to flow into the above mentioned Storm Water and Surface Water Runoff Sewer System.</p>
                <p><strong>Section 26. Use of Other Structures and Vehicles </strong>No structure of a temporary character, trailer, boat trailer, boat, truc, commercial vehicle, recreational vehicle (RV), camper shell, all terrain vehicle (ATV), camper or camping trailer, tent, shack, garage, barn, dog house, or other outbuilding shall be either used or located on any Lot, or adjacent to any Lot, or right-of-way within the Subdivision at any time, or used as a residence either termporarily or permanently. No automobile, which is inoperable, shall be habitually or repeatedly parked or kept on any Lot (except in the garage) in Park Ridge.</p>
                <p><strong>Section 27. Animals </strong>No animals, livestock, or poultry of any kind shall be raised, bred, or kept on any Lot, except that dogs, cats, or other household pets may be kept, provided that they are not kept, bred, or maintained for any commercial purpose.</p>
                <p><strong>Section 28. Drilling, Refining, Quarrying, and Mining Operations </strong>No oil drilling, oil development operations, oil refining, quarrying, or mining operations of any kind shall be permitted upon or in any Lot. No derrick or other structure designed for the use in boring for oil or natural gas shall be erected, maintained, or permitted upon any Lot.</p>
                <p><strong>Section 29. Signs </strong>No sign of any kind shall be displayed to the public view on any Lot except one sign of not more than five square feet advertising such Lot for sale or rent, or used by a builder to advertise such Lot during the construction and sales period. The Developer or a builder with approval by the Developer, shall have the right to (a) erect larger signs allowed by applicable zoning regulations when advertising the subdivision and (b) place signs on Lots designating the Lot number of said Lots. This restriction shall not prohibit placement of occupant name signs and Lot numbers as allowed by applicable zoning regulations.</p>
                <p><strong>Section 30. Trash and Garbage </strong>No Lot shall be used or maintained as a dumping ground for rubbish. Trash, garbage, or other waste shall not be kept except in sanitary containers. No outside incinerators shall be kept or allowed on any Lot.</p>
                <p><strong>Section 31. Common Area Maintenance </strong>For any Common Areas located between a Lot line and the waters edge of a lake or pond, as shown on the plat, the Owner of said Lot shall be solely responsible for the landscaping and lawn maintenance.</p>
                <p><strong>Section 32. Street Signs </strong>It shall be the responsibility of the Association to maintain and repair all street signs which identify particular streets in the subdivision. The Association shall not be responsible for the installation, maintenance or replacement of any traffic control signs located in the subdivision.</p>
                <p><strong>Section 33. Fires </strong>No outdoor fires for the purpose of burning leaves, grass, or other forms of trash shall be permitted to burn upon any street roadway or Lot in this Subdivision, other than that as related to the construction of a dwelling unit.</p>
                <p><strong>Section 34. Common Area Maintenance </strong>For any Common Areas located between a Lot line and the waters edge of a lake or pond, as shown on the plat, the Owner of said Lot shall be solely responsible for the landscaping and lawn maintenance.</p>
                <p><strong>Section 35. Rights of Ingress and Egress </strong>The rights of ingress and egress to the Subdivision shall only be in such locations as shown on the Plans and Specifications of the Subdivision.</p>
                <p><strong>Section 36. Enforceability </strong>The Association, the Developer, and any Owner shall have the right to enforce, by any proceeding at law or in equity, all restrictions, conditions, covenants, reservations, liens, and charges now or hereafter imposed by the provisions of these Restrictions. Failure by the Association, the Developer, or by any Owner to enforce any covenant or restriction herein contained shall in no event be deemed a waiver of the right to do so thereafter.</p>
                <p><strong>Section 37. Partial Invalidation </strong>Invalidation of any one of the provisions of this Dedication by judgment or court order shall in no wise affect any other provision(s) which shall remain in full force and effect.</p>
                <p><strong>Section 38. Covenants, Restrictions, and Extensions </strong>The covenants and restrictions herein contained shall run with the land, and be effective for a term of twenty (20) years from the date this Dedication is recorded, after which time they shall automatically be extended for successive periods of ten (10) years; provided this Dedication may be amended by an instrument signed by not less than 75% of the Lot Owners, and provided further, the Developer, its successors, or assigns shall, with the approval of the City of Warsaw Plan Commission, have the exclusive right for a period of two (2) years from the date of recording of this Dedication to amend any of the provisions of this Dedication.</p>
                </AccordionItem>
            </AccordionItem>
                </Accordion>
        </div>
    </div>
    )
}

export default Covenants;